# Generated by Django 4.1.3 on 2022-11-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=150, null=True)),
                ('quantity', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ManyToManyField(to='alfreed.workers')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField()),
                ('type', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('person', models.ManyToManyField(to='alfreed.workers')),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alfreed.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receipiant', models.ManyToManyField(to='alfreed.workers')),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alfreed.sales')),
            ],
        ),
    ]
