# Generated by Django 4.1.3 on 2022-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfreed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomes',
            name='person',
        ),
        migrations.RemoveField(
            model_name='outcomes',
            name='sales',
        ),
        migrations.AddField(
            model_name='sales',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='outcome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='person',
            field=models.ManyToManyField(related_name='person', to='alfreed.workers'),
        ),
        migrations.AddField(
            model_name='sales',
            name='receipiant',
            field=models.ManyToManyField(related_name='receipiant', to='alfreed.workers'),
        ),
        migrations.AddField(
            model_name='sales',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='products',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='worker',
            field=models.ManyToManyField(blank=True, to='alfreed.workers'),
        ),
        migrations.DeleteModel(
            name='Incomes',
        ),
        migrations.DeleteModel(
            name='Outcomes',
        ),
    ]
