# Generated by Django 4.1.3 on 2022-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfreed', '0003_alter_sales_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='outcome',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
