# Generated by Django 4.1.3 on 2022-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfreed', '0004_alter_sales_income_alter_sales_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
